# Font configuration
[font]
normal = { family = "FiraMono Nerd Font", style = "Regular"}
bold = { family = "FiraMono Nerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font", style = "Bold Italic" }

# Point size
size = 12

offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }
